dist: precise
sudo: false
language: php

before_script:
- phpenv config-rm xdebug.ini || return 0
- composer install

script:
- vendor/bin/phpunit

jobs:
  include:
  - stage: Unit Test + Code Style Fixing
    php: 5.3
  - stage: Unit Test + Code Style Fixing
    php: 5.6
    script:
    - curl -L http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer
    - chmod a+x php-cs-fixer
    - git checkout $TRAVIS_BRANCH
    - ./php-cs-fixer fix --config=.php-cs.dist --cache-file=.php-cs.cache --diff --dry-run --verbose .
    - rm php-cs-fixer
    - vendor/bin/phpunit
  - stage: deploy
    php: 5.6
    before_script: skip
    script:
    - if [[ "$TRAVIS_TAG" ]]; then ./release/build_release_package.sh ; fi
    deploy:
      provider: releases
      api_key:
        secure: dVA1TQcoh2IlFwhOG8v97vgxdWaaGdjKK+s/WcF/exWsr3PnPH7eNWaoEJEVYgyGzJn1MqXQNBJv7rFdAg4ZWzeT185FdQgYKIquaAMABtzeWhNWgimekQMnd2Fotk1wkYihKx28JNOk/J4sP6nVTypqJoeIeB2WAZpTvlacx+OsWtApURzrK/WWT0dUyBXQZX+Qb5SMTi954DOpiugdijswCvztzKZYLc+KgjEPJ5lSJBOitxTyfeURTLgeAqBpIO48p1+jddzwORc9eXSxnQlhplNJKQ33Yc+sWv1osPLWxPB5a5x6IgqbHP8tzsChTvaCWSgWUEXgvq8rMTkXaZtBQoxpjeSjppy5x5Q4GReoDdjNzA5buDQQiK/q4VKK6tn15Na6FYa6YAMF8qMT9of1g7/Km/F5B9nuLXCJZ4ikpW+32zg0q+IRh29fwhcmzEep25srERhF4SJC7VQRTnkb3XHsPkJtiqKLGxyilfVKb3gM8JiwJt/snY+a6X1HpUI1AWZxm1nmhECKXkAwdiwEj6xRVxV5LqjIndHm67J7JzEXjvFGT3iOLVwjh/lHlSCA6P195wNrbXv4PcpTHZA5NvrLKr+CsPGuopko1sbFf3RJW/Jg64pwNGibLqG8xTF02isqx2Ezr1KFD8JHfxOJgXe23fGEMc7vxYNBbko=
      file: shopgate-cart-integration-sdk.zip
      skip_cleanup: true
      on:
        tags: true

notifications:
  slack:
    rooms:
      secure: jVUmUjLGJiQ61J565blTHQx9W7qriYGjxqa0WJpHBW74Een3ODOjHdVft+Vw46UQThGUWzZKZq2zFDPsz7ndFHm3xYgGHrdnOG8TM4CDtjw7Ic2HBXvp/LoxW4hT2+DC0eqWeUsvHrtDHcqOFv2DFBjKXIFa78H2Ke/oTvt3LmpY4ET1qWQNah+78/aaU7diNLrAXLRVRVhu7WGD48meHznMtJ8UvBjNMrTeLhWrmnrx8WXakWAFkVqvBQRiHSeePQ1YDPQ1TRG8Hw4ahkwUTZ4sD1gnUnrRS3a+jsiF0PZUJD2tYQskPUUFzWVWqhBmfI5oaFdjlwhZ76RGp6p5FRwJH80/+AV+k4wOKO97HzPPXduTqwegsrswDX776E8msRZEjP5mM7OllT/c+ecNuU4UtFMNWBwC2yfb6Ho1fPQhG7TmRw6u19bK1KflI5n3ptJqldetbjaaDQLcOrd21zY96i4x1W3p8ABjriMO9bfULkgQ2E5kd5DIr/HNe5TQjANRoGs+h+vv4RFFcd6oXLwtJXguqHspcNiIrqnNkCIhAt81f+3udOp9UsfxuDDBmBu0CWuXl3ObYF/I6DuBFa6cZRWW/A/bhXmK9yprTjMDDVzhiTxRgRCT44ia1bcPQ7yYsj5/BCtRoh+sJh17uq1bbhQP8DDlr4/mIahZaoA=
    on_success: change
    on_failure: always
