language: php

matrix:
  include:
    - php: 5.6

before_script:
- curl -L http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer
- chmod a+x php-cs-fixer

script:
- ./php-cs-fixer fix --config=.php-cs.dist --cache-file=.php-cs.cache --diff --dry-run --verbose .
- if [[  $? != 0 ]]; then ./clean.sh; fi


